version: "3.9"

services:
  mongodb-scratch:
    image: mongo:6.0.2
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend-node-scratch:
    depends_on:
      mongodb-scratch:
        condition: service_healthy
    build: backend
    env_file: .env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}

volumes:
  db:
